kind: Deployment
apiVersion: apps/v1
metadata:
  name: staticwebsitehosting
spec:
  template:
    metadata:
      labels:
        app: staticwebsitehosting
    spec:
      containers:
      - name: staticwebsitehosting
        image: 363412468025.dkr.ecr.us-east-2.amazonaws.com/staticwebsitehosting:latest
  selector:
    matchLabels:
      app: staticwebsitehosting
---
kind: Service
apiVersion: v1
metadata:
  name: staticwebsitehosting
spec:
  type: LoadBalancer
  selector:
    app: staticwebsitehosting
  ports:
  - name: http
    port: 5002
    targetPort: 3002
